default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: RailsAPIDatabase
  username: postgres  # Keep this for local dev
  password: ssb13032004
  host: localhost

test:
  <<: *default
  database: RailsAPIDatabase_test
  username: postgres
  password: ssb13032004
  host: localhost

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
