default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgres  # Replace with your PostgreSQL username
  password: ssb13032004 # Replace with your PostgreSQL password
  host: localhost

development:
  <<: *default
  database: RailsAPIDatabase

test:
  <<: *default
  database: RailsAPIDatabase_test

production:
  <<: *default
  database: RailsAPIDatabase_production
  url: <%= ENV['DATABASE_URL'] %> # Used for deployment
